### PR TITLE
Added SSL support

### PR DESCRIPTION
**Pull request by Fmstrat**
- 99% of this is for SSL support
- The last commit (https://github.com/genielabs/HomeGenie-Android/commit/7a3486a4f6fe1990e47e9593646538435bf190a4), also fixes a battery drain bug where the netty loop would continue to run even when the device was turned off or the application was backgrounded
- Accompanies the pull request for the client lib here: https://github.com/genielabs/HomeGenie-Android-ClientLib/pull/1

### CODE REVIEW

**Comment by Fmstrat** [comment]
Forgot to reference ongoing conversation related to SSL requests in the forum: http://www.homegenie.it/forum/index.php?topic=1001.0

Thanks.

**Comment by Fmstrat** [comment]
Just wanted to do a status check on this and the corresponding library pull (https://github.com/genielabs/HomeGenie-Android-ClientLib/pull/1) and see if there was a plan to include. Thanks!

**Comment by genielabs** [comment]
Yes, I will merge pull requests in both repos (lib and client) soon.

**Comment by genielabs** [comment]
@Fmstrat pull request merged and also pushed some other improvement/fixes to the app, please have a test

**Pull request merged**
